### ISSUE TITLE
Support for Azure OpenAI API?

### ISSUE THREAD

**Issue by Ignoramus0817** [Psycoy/MixEval#12]
Does MixEval work with Azure OpenAI API (as judgement models)? Or how can I modify the codes to get it to work?

**Comment by Psycoy** [comment]
Hey Chiwei, 

I have added the feature. 
Specify the `--api_base_url` if you wish to use other api such as llama.cpp server and Azure OpenAI API.

**Comment by Ignoramus0817** [comment]
Thanks for adding the feature!
Actually I closed it before as I found it easy to modify the codes to work with Azure, but having an official solution is always better :)
