### ISSUE TITLE
Problem in Inference of Local Chat Model

### ISSUE THREAD

**Issue by carstendraschner** [Psycoy/MixEval#23]
Hello :)

I face an Issues with Inference by using local chat. 
as local chat overwrites build transformer of Base it does not include the default padding = left which is needed for inference. 
I created a PR to solve this issue:

https://github.com/Psycoy/MixEval/pull/22

regards
Carsten

**Comment by Psycoy** [comment]
Hi Carsten, thank you for your contribution! I have merged the pull request
