### ISSUE TITLE
Add Mistral Large 2 (123B) and Mistral NeMo (12B)

### ISSUE THREAD

**Issue by carterprince** [Psycoy/MixEval#26]
See the updated Mistral API docs: https://docs.mistral.ai/getting-started/models/

## Mistral Large 2 (123B)

Hugging Face: https://huggingface.co/mistralai/Mistral-Large-Instruct-2407
Mistral Blogpost: https://mistral.ai/news/mistral-large-2407/

Since this eval seems to just point to `mistral-large-latest`, all you (should) have to do is re-run it and maybe update the front-facing model name, unless you wish to keep the entry for the old Mistral Large.

## Mistral NeMo (12B)

Hugging Face: https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407
Mistral Blogpost: https://mistral.ai/news/mistral-nemo/

Impressive models, very exciting.

**Comment by carstendraschner** [comment]
hi @carterprince , I could imagine that we might need to wait til a pip installable transformers version is available

**Comment by carterprince** [comment]
I believe there is [one available](https://huggingface.co/mistralai/Mistral-Large-Instruct-2407#transformers) (I could be wrong), but doesn't this eval use the Mistral API anyways?

See the implementation of `mistral_large.py`:

https://github.com/Psycoy/MixEval/blob/c2ccb6b2459057e784737d771d334101b364be50/mix_eval/models/mistral_large.py#L6-L36

**Comment by carstendraschner** [comment]
Ah I See, I thought you'd like to run it locally. my message was more of a comment than a fully reliable statement based on: https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407/discussions/35

**Comment by Psycoy** [comment]
> See the updated Mistral API docs: https://docs.mistral.ai/getting-started/models/
> 
> ## Mistral Large 2 (123B)
> Hugging Face: https://huggingface.co/mistralai/Mistral-Large-Instruct-2407 Mistral Blogpost: https://mistral.ai/news/mistral-large-2407/
> 
> Since this eval seems to just point to `mistral-large-latest`, all you (should) have to do is re-run it and maybe update the front-facing model name, unless you wish to keep the entry for the old Mistral Large.
> 
> ## Mistral NeMo (12B)
> Hugging Face: https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407 Mistral Blogpost: https://mistral.ai/news/mistral-nemo/
> 
> Impressive models, very exciting.

Hi @carterprince , 

it's been updated :)
