### ISSUE TITLE
How to submit my model to the Leaderboard?

### ISSUE THREAD

**Issue by Waneila** [Psycoy/MixEval#27]

**Comment by Psycoy** [comment]
Hi, Waneila, you can run the test on MixEval-Hard and MixEval and give us the screenshot here
Please make sure to adhere to the instructions in the repo

thanks
Jinjie

**Comment by Waneila** [comment]
Hi Jinjie,

Here are the results of our model, Spark4.0, on MixEval-Hard and MixEval for the 20240601 version. Please include our model name in the leaderboard.

Thank you, and I wish you a pleasant day.

Best regards,
Waneila




At 2024-07-26 08:34:53, "Jinjie Ni" ***@***.***> wrote:

Hi, Waneila, you can run the test on MixEval-Hard and MixEval and give us the screenshot here
Please make sure to adhere to the instructions in the repo

thanks
Jinjie

**Comment by Waneila** [comment]
I have already replied to the issue via email and submitted our results. Please confirm if you have received them.

thanks
Waneila

**Comment by Psycoy** [comment]
Hi @Waneila ,

I cannot see the results here, was it attached as an image?

**Comment by Waneila** [comment]
Hi Jinjie,

I'm sorry, the image was sent via email, so it might not display here. Let me resend the screenshot.
Here are the results of our model, **Spark4.0**, on **MixEval-Hard** and **MixEval** for the **20240601 version**. Please include our model name in the leaderboard.
<img width="201" alt="mixeval_hard" src="https://github.com/user-attachments/assets/2263a254-cdb8-45e7-ac13-74f5b09099f5">
<img width="201" alt="mixeval" src="https://github.com/user-attachments/assets/ebf59045-6b71-4dae-b378-2a87cf0e0027">

Thank you, and I wish you a pleasant day.

Best regards,
Waneila

**Comment by Psycoy** [comment]
Hi @Waneila ,

Is there any technical report / paper for your models?
We will only include models that are known to the public to the leaderboard. 
If there is one, would you kindly give us a pointer? We will look into it.
If not, maybe you can first indicate the results in the paper and contact us to add to the leaderboard as soon as it's released. 

Have a nice day!

**Comment by Waneila** [comment]
Hi Jinjie,

This is the access address for our model: [https://xinghuo.xfyun.cn/spark](). You are welcome to visit this interface.

thanks
Waneila

**Comment by Waneila** [comment]
Hi Jinjie,

We have already provided our model's homepage. When can it be added to the leaderboard approximately? If there are any issues, please contact me promptly.

thanks
Waneila

**Comment by Psycoy** [comment]
Hi @Waneila ,

It's alr on the leaderboard. Please check if you could see it.

**Comment by Waneila** [comment]
Hi Jinjie,

We have already seen our model on the leaderboard, thanks for your support.

**Comment by Waneila** [comment]
Hi Jinjie,

Our model, **Spark 4.0**, has been updated to **Spark 4.5**. We are pleased to announce that compared to the previous version, our latest model has achieved significant improvements in **MixEval-Hard** and **MixEval tasks**. Here are the results of our latest model, **Spark 4.5**, on **MixEval-Hard** and **MixEval** for the **20240601 version**. Please update our model in the leaderboard. 
<img width="206" alt="mixeval-hard" src="https://github.com/user-attachments/assets/da829817-1358-4e0b-a300-7b2527f484c8">
<img width="208" alt="mixeval" src="https://github.com/user-attachments/assets/8abe3266-5b46-46a9-b379-6cc62a89c0f6">

Thank you, and I wish you a nice day!
Waneila

**Comment by Waneila** [comment]
Hi Jinjie,

I'm sorry, our latest model is named **Spark 4.0-2024-10-14**, not **Spark 4.5**. Please take note.

Thanks,
Waneila

**Comment by Psycoy** [comment]
Hi Waneila, 

Noted, we will update the results soon

**Comment by Waneila** [comment]
Hi Jinjie,

When can the update be completed?

**Comment by Psycoy** [comment]
> Hi Jinjie,
> 
> When can the update be completed?

Hi @Waneila ,

We are currently reviewing some models to be added to the leaderboard.
We will update the results once it's done.
