### ISSUE TITLE
What are the specific models used to compute difficulty score for MixEval-Hard?

### ISSUE THREAD

**Issue by calvinh99** [Psycoy/MixEval#29]
Hi @Psycoy ,

I couldn't find which models were used in the difficulty score calculation of MixEval-Hard. Would it be possible to disclose the specific models/model ids?

Thanks,
Calvin

**Comment by Psycoy** [comment]
Hi Calvin,

We used all the models in the paper, except gpt-4o, qwen-max, and mammoth 2 (which were updated later)
