### ISSUE TITLE
Are you considering open sourcing more data and code?

### ISSUE THREAD

**Issue by weizier** [Psycoy/MixEval#36]
I like your great idea and method, so I want to try it by myself. Are you considering open sourcing the 2m query data or the construction code like how to find similar query in existed eval set and the correlation analysis code? Again, thank you very much.

**Comment by Psycoy** [comment]
Hi @weizier ,

At this moment, we are not open-sourcing the exact web query data or pipeline, as it would be easier for others to hack the resampled benchmark versions, and also we have another on-going project.

If you are working with the text data only, using user queries from the chatbot arena or sharegpt is a good alternative to web queries.
