### ISSUE TITLE
Metrics calculation could become wrong

### ISSUE THREAD

**Issue by carstendraschner** [Psycoy/MixEval#37]
Hi @Psycoy 

I am using different datasets for benchmarking. I see in the metrics computation some simplifications which would lead to errors that should be fixed:

1) You divide by 2 assuming the datasets for freeform and mc are always same sized, why might weight by their lengths, right? https://github.com/Psycoy/MixEval/blob/64934d25c17ab6ff140e63900982f990c1b0b02a/mix_eval/compute_metrics.py#L744
2) If a dataset name is available in both mp and ff, then the aggregated score is not accumulated but overwritten https://github.com/Psycoy/MixEval/blob/64934d25c17ab6ff140e63900982f990c1b0b02a/mix_eval/compute_metrics.py#L746

regards
Carsten

**Comment by Psycoy** [comment]
Hi @carstendraschner ,

Thanks for pointing this out!

**Comment by carstendraschner** [comment]
are you planning to change the code or should I open a PR?

**Comment by Psycoy** [comment]
I fixed the second issue, but have got time to do the first one. Is it possible for you to do some help? Thanks :-D
