### ISSUE TITLE
Default SYSTEM_MESSAGE for Llama 3 Instruct is "You are a pirate chatbot who always responds in pirate speak!"

### ISSUE THREAD

**Issue by lhl** [Psycoy/MixEval#4]
It seems like this seems would generate bad benchmark results?

https://github.com/Psycoy/MixEval/blob/main/mix_eval/models/llama_3_8b_instruct.py#L18C1-L18C160
```
        self.SYSTEM_MESSAGE = {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"} # set to None if no system message
```

Note this seems to be an issue for llama_3_70b_instruct.py and zephyr_7b_beta.py

Is this what was run to generate the scores on https://mixeval.github.io/#leaderboard ?!?!

**Comment by Psycoy** [comment]
No, it's just for testing. We tested both system prompts. (the one shown on the [Llama 3 hf repo](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) or set to None)

**Comment by jmercat** [comment]
Could you set the default to None on the main ?

**Comment by Psycoy** [comment]
@jmercat Done
