### ISSUE TITLE
Model Meta-Llama-3.1-8B-Instruct is not available in the registry.

### ISSUE THREAD

**Issue by iseesaw** [Psycoy/MixEval#41]
Should I register the model if I only want to compute scores on my response files?

**Comment by Psycoy** [comment]
Yes, you need to register the model when computing the scores with the `compute_metrics.py` script.

**Comment by iseesaw** [comment]
Is it possible to remove the model list from the code? I’m not sure why I need to register my own models.

**Comment by Psycoy** [comment]
Hi @iseesaw ,

Sorry for the inconvenience. 
When the `compute_metrics.py` is solely used for the score computation, it's very simple to register your model, just put your model name in the `mix_eval/models/__init__.py`, e.g., "Meta-Llama-3.1-8B-Instruct: None"
