### ISSUE TITLE
Source of data on leaderboard?

### ISSUE THREAD

**Issue by lewtun** [Psycoy/MixEval#42]
Hello, I'd like to compute an up-to-date regression from your public leaderboard: https://mixeval.github.io/#leaderboard

I could not find the source of that data on the repo - is it available somewhere?

I can of course scrape the website, but it would be much simpler if the source data was easy to access. Also, it would be great to see the code used for the regression analysis in the paper to compare with my own method:

![Screenshot 2024-09-23 at 11 24 32](https://github.com/user-attachments/assets/0e2c3375-6028-4e25-8209-2efb8ab76710)

Thank you!

**Comment by Psycoy** [comment]
[scores_chat.xlsx](https://github.com/user-attachments/files/17095520/scores_chat.xlsx)

Hi @lewtun , you can find the scores above. 

Sorry that I cannot the plot script any more :( 
But it should be easy given the scores

**Comment by lewtun** [comment]
Thank you!
