### ISSUE TITLE
Is there any data set from HumanEval, please provide it

### ISSUE THREAD

**Issue by xiaoxiaoimg** [Psycoy/MixEval#49]
Is there any data set from HumanEval, please provide it

**Comment by Psycoy** [comment]
hi, there are only few HumanEval data points contained in the resulting data of MixEval. It's already contained in the released MixEval dataset (converted to multiple-choice questions)

**Comment by xiaoxiaoimg** [comment]
I searched all the json files in the mix_eval/data directory. No result was found when benchmark_name was Human-Eval. Could you please provide the address of the specific dataset?

**Comment by Psycoy** [comment]
BTW, as shown in the Figure 5 of the paper, there're only 1-2 HumanEval data points in MixEval, so I think it's impact is ignorable.
