### ISSUE TITLE
The answer set here is a 100% wrong.

### ISSUE THREAD

**Issue by XapaJIaMnu-at-meta** [Psycoy/MixEval#8]
https://github.com/Psycoy/MixEval/blob/03ee6e606d3b5af8fdb2b1da711f5672d0c98482/mix_eval/data/mixeval-2024-06-01/mixeval/free-form.json#L672

The answerset is a bunch of buzzwords from the harry potter books, it should be just Hufflepuff

**Comment by Psycoy** [comment]
Hi Nikolay, thanks for proposing this issue. 

**This is the problem of the original TriviaQA annotation**. Such annotation errors have a negligible number, so they won't affect the result significantly.
