### ISSUE TITLE
Are the evaluation data from different benchmarks available?

### ISSUE THREAD

**Issue by felipemaiapolo** [Psycoy/MixEval#9]
Dear authors,

Congrats on the nice work!

I am wondering if the data you collected from the different benchmarks you consider available somewhere.

Thank you!
Felipe

**Comment by Psycoy** [comment]
Hey Felipe, 

The benchmarks are all publically available, you refer to our [paper](https://arxiv.org/abs/2406.06565) to see the exact benchmarks in our benchmark pool.
